# Generated by Django 4.2.23 on 2025-07-28 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
